bvp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('vpi/', include('vpi.urls')),
    path('data/', include('data.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout, name='logout')
]

dashboard/urls.py
from django.urls import path

import data.views as dataviews
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('<int:dashboard_id>', views.general_dashboard, name='dashboard'),
    path('project/<project_number>', views.project_dashboard, name='project_dashboard'),
    path('reports', views.reports, name='reports'),
    path('report', views.reports_detail, name='report'),
    path('ajax/get_pms', dataviews.get_prestatiemetingen, name='get_prestatiemetingen')
]

data/urls.py
from django.urls import path

from . import views

app_name = 'data'
urlpatterns = [
    path('upload', views.upload, name='upload'),
    path('forms', views.forms, name='forms'),
    path('forms/<int:form_id>', views.forms_detail, name='forms_detail'),
    path('projects', views.projects_view, name='projects'),
    path('prestatiemeting/<int:prestatiemeting_id>/', views.prestatiemeting, name='prestatiemeting'),
    path('prestatiemeting/<int:prestatiemeting_id>/config/', views.prestatiemeting_config, name='prestatiemeting_config'),
    path('prestatiemeting/<int:prestatiemeting_id>/export/', views.export_excel, name='export_excel'),
    path('ajax/get_pms', views.get_prestatiemetingen, name='get_prestatiemetingen'),
]

data/models/forms.py
from django.contrib.auth.models import User
from django.db import models


class Form(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    user = models.ManyToManyField(User)
    last_filled = models.DateTimeField()

    def __str__(self):
        return self.name

    def get_form_fields(self):
        """
        Get form fields from a Form object
        @return: QuerySet of formfields
        """
        return self.objects.formfield_set.all()


class FormField(models.Model):
    form = models.ForeignKey(Form, on_delete=models.CASCADE)
    text = models.TextField(null=True, blank=True)
    order = models.IntegerField(null=True, blank=True)
    allow_explanation = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class FormFieldMultipleChoiceAnswer(models.Model):
    answer = models.TextField()
    form_field = models.ForeignKey(FormField, on_delete=models.CASCADE)

    def __str__(self):
        return self.answer

data/models/other.py
from django.apps import apps
from django.db import models
from django.db.models import QuerySet


class DataContainer:
    model: models.Model = None
    _data: QuerySet = None
    tmp_data: QuerySet = None

    def __init__(self, model_name):
        self.model = apps.get_model(app_label='data', model_name=model_name)

    def apply_filters(self, filters):
        """
        Apply filters so Datacontainer object
        @param filters: Filters in dictionary format
        """
        self._data = self.model.objects.filter(**filters)

    def annotate(self, annotation):
        """
        Apply annotation to datacontainer object
        @param annotation: annotation in dictionary format
        """
        self._data = self._data.annotate(**annotation)

    def aggregate(self, aggregation):
        """
        Apply aggregation to datacontainer object
        @param aggregation: aggregation in dictionary format
        """
        self._data = self._data.aggregate(**aggregation)

    @property
    def data(self):
        """
        data property of datacontainer object
        @return: Queryset
        """
        return self._data

data/models/project.py
from django.db import models
from django.contrib.admin.utils import quote


class Address(models.Model):
    city = models.CharField(max_length=30)
    postal_code = models.CharField(max_length=10)
    street = models.CharField(max_length=20)
    number = models.IntegerField()
    number_addition = models.CharField(max_length=5, null=True, blank=True)

    def __str__(self):
        return f'{self.street} {self.number}{self.number_addition if self.number_addition else ""}, {self.postal_code} {self.city}'


class Opdrachtgever(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255, blank=True, null=True)
    address = models.OneToOneField(Address, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class OpdrachtgeverContactPersoon(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    address = models.OneToOneField(Address, on_delete=models.CASCADE, blank=True, null=True)
    phone = models.CharField(max_length=15)
    email = models.CharField(max_length=30)
    opdrachtgever = models.ForeignKey(Opdrachtgever, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.firstname} {self.lastname}'


class Project(models.Model):
    # TODO add surrogate primary key on next database drop
    number = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    opdrachtgever = models.ForeignKey(Opdrachtgever, on_delete=models.CASCADE, null=True)
    object_amount = models.IntegerField(default=1)
    vpis = models.ManyToManyField(to='vpi.VPI', blank=True)

    def __str__(self):
        return f'{self.number}: {self.name}'

    def encode_number(self):
        return quote(self.number)


class ProjectGoal(models.Model):
    number = models.IntegerField()
    project = models.OneToOneField(Project, on_delete=models.CASCADE)
    goal = models.TextField()

    def __str__(self):
        return f'{self.project.number}:{self.project.name} - Projectdoel {self.number}'


class ProjectActiviteit(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    code = models.CharField(max_length=20)
    description = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.code}{self.description}'


class ProjectFase(models.Model):
    INRICHTING = 'INR'
    ONTWERP = 'ONT'
    UITVOER = 'UIT'
    OPLEVERING = 'OPL'
    OVERIG = 'OVG'
    CHOICES = [
        (INRICHTING, 'Inrichting'),
        (ONTWERP, 'Ontwerp'),
        (UITVOER, 'Uitvoer'),
        (OPLEVERING, 'Oplevering'),
        (OVERIG, 'Overig')
    ]
    fase = models.CharField(max_length=3, choices=CHOICES)
    description = models.TextField()
    activities = models.ManyToManyField(ProjectActiviteit)

    def __str__(self):
        return self.fase

data/views.py
from datetime import datetime

import xlrd
import pandas as pd
from django.contrib import messages
from django.contrib.auth.decorators import permission_required, login_required
from django.core.exceptions import ValidationError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from tablib import Dataset

from data.helpers.excel import export_prestatiemeting
from data.helpers.validator import validate_prestatiemeting_import
from vpi.models import VPI, VPIValuePrestatiemeting
from .models.forms import Form
from .models.prestatiemeting import PrestatiemetingTheme, Prestatiemeting, \
    PrestatiemetingConfig, PrestatiemetingResult, PrestatiemetingAnswer
from .models.project import ProjectActiviteit, Project
from .models.sources import Sap
from .resources import UltimoResource, SapResource


@login_required
@permission_required('perms.input_datafile')
def upload(request):
    """
    Upload view
    @param request: http request object
    @return: Upload view
    """
    if request.method == 'POST':
        if not request.FILES['datafile'] is None:
            if request.POST.get('source') == 'prestatiemeting':
                upload_prestatiemeting(request)

            elif request.POST.get('source') == 'ultimo':
                upload_ultimo(request)

            elif request.POST.get('source') == 'sap':
                upload_sap(request)
        else:
            print('Er is geen bestand geupload')
    return render(request, 'data/upload.html')


def upload_sap(request):
    """
    Adapt SAP column headers and Upload to database.
    @param request: http request object
    """
    file = request.FILES['datafile']
    data = pd.read_excel(file)

    # determine project number
    uploaded_project = None

    projects = Project.objects.all()
    for project in projects:
        if project.number in data['Object'].iloc[0]:
            uploaded_project = project

    data.rename(columns={
        data.columns[0]: "object",
        data.columns[1]: "wbs_element",
        data.columns[2]: "objectomschrijving",
        data.columns[3]: "kost_soort",
        data.columns[4]: "omschrijving",
        data.columns[5]: "personeelsnummer",
        data.columns[6]: "naam_kost_soort",
        data.columns[7]: "achternaam_voornaam",
        data.columns[8]: "per",
        data.columns[9]: "aan_afw",
        data.columns[10]: "parprs",
        data.columns[11]: "doc_number",
        data.columns[12]: "doc_datum",
        data.columns[13]: "boek_datum",
        data.columns[14]: "hoeveelheid_totaal",
        data.columns[15]: "he",
        data.columns[16]: "waarde_co_valuta",
        data.columns[17]: "omschrijving2",
        data.columns[18]: "categorie",
        data.columns[19]: "jaar",
        data.columns[20]: "maand",
        data.columns[21]: "week",
        data.columns[22]: "surcharge",
        data.columns[23]: "overhead",
        data.columns[24]: "besteltekst",
    }, inplace=True)

    resource = SapResource()
    dataset = Dataset()
    dataset.load(data)
    result = resource.import_data(dataset, dry_run=True, raise_errors=True)  # Test the data import

    if not result.has_errors():
        resource.import_data(dataset, dry_run=False)  # Actually import now

    save_project_activiteiten(uploaded_project)


def save_project_activiteiten(project):
    """
    Extract all project activities from Sap import and save them to database.
    @param project: project object to link to the project activity
    """
    unique_activiteit_codes = Sap.objects.order_by('object').values('object', 'objectomschrijving').distinct()

    for data in unique_activiteit_codes:
        ProjectActiviteit.objects.get_or_create(project=project, code=data['object'],
                                                description=data['objectomschrijving'])


def upload_ultimo(request):
    """
    Handle ultimo excel sheet.
    @param request: http request object
    @return: redirect to upload page on successful upload
    """
    resource = UltimoResource()
    dataset = Dataset()

    dataset.load(request.FILES['datafile'].read())

    try:
        result = resource.import_data(dataset, dry_run=True, raise_errors=True)  # Test the data import
    except ValidationError as err:
        messages.error(request, f'Er is een validatie error opgetreden: {err}')
        return redirect('data:upload')

    if not result.has_errors():
        result = resource.import_data(dataset, dry_run=False)  # Actually import now
        messages.success(request, f'{result.total_rows} records geupload.')


def upload_prestatiemeting(request):
    """
    Upload function for prestatiemeting Excel forms
    @param request: http request object
    """
    data = request.FILES['datafile']
    book = xlrd.open_workbook(file_contents=data.read())
    sheet = book.sheet_by_index(0)

    error = validate_prestatiemeting_import(sheet)
    print(error)

    if error is None:
        prestatiemeting_id = int(sheet.cell_value(0, 0).split('=')[1])
        pm = Prestatiemeting.objects.get(pk=prestatiemeting_id)

        pm.save_excel_results(sheet)
        pm.filled_og = datetime.now()
        pm.uploaded_by = request.user
        print(data)
        pm.excel_file = data
        pm.save()

        if pm.is_finished():
            VPIValuePrestatiemeting(vpi_id=1, prestatiemeting=pm, happened=pm.date_finished,
                                    project_number=pm.project.number)
    else:
        messages.error(request, error)
        print(messages)


@login_required
@permission_required('perms.view_forms')
def forms(request):
    """
    Overview for forms and prestatiemetingen
    @param request: http request object
    @return: forms view
    """
    if request.POST:
        if 'prestatiemeting_upload' in request.POST:
            redirect('data:upload')

        project = Project.objects.get(pk=request.POST.get('project_select'))
        pm_select = request.POST.get('pm_select')

        if 'prestatiemeting_conf' in request.POST:
            pm = Prestatiemeting.objects.get_or_create(project=project, number=pm_select)
            if pm[0].is_submitted_by_og() is False and pm[0].is_submitted_by_on() is False:
                return redirect('data:prestatiemeting_config', prestatiemeting_id=pm[0].id)
            else:
                messages.error(request, 'Prestatiemeting is al ingevuld. Configuratie kan niet meer worden'
                                        ' gewijzigd.')
        if 'prestatiemeting_fill' in request.POST:
            try:
                pm = Prestatiemeting.objects.get(project=project, number=pm_select)
                return redirect('data:prestatiemeting', prestatiemeting_id=pm.id)
            except Prestatiemeting.DoesNotExist:
                messages.error(request, 'Deze prestatiemeting bestaat nog niet. Configureer deze eerst.')

    context = {
        'projects': Project.objects.all(),
        'forms': request.user.form_set.all()
    }
    return render(request, 'data/forms.html', context=context)


@login_required
@permission_required('perms.view_forms')
def prestatiemeting_config(request, prestatiemeting_id):
    """
    View for configuring a prestatiemeting
    @param request: http request object
    @param prestatiemeting_id: prestatiemeting id
    @return: config view
    """
    if request.POST:
        PrestatiemetingConfig.objects.filter(prestatiemeting_id=prestatiemeting_id).delete()

        for option in request.POST.getlist('question_checkbox'):
            PrestatiemetingConfig(prestatiemeting_id=prestatiemeting_id, question_id=option).save()

        return redirect('data:forms')

    pm = Prestatiemeting.objects.get(pk=prestatiemeting_id)
    themes = PrestatiemetingTheme.objects.all()

    return render(request, 'data/prestatiemeting_config.html', {'prestatiemeting': pm,
                                                                'themes': themes})


def get_prestatiemetingen(request):
    """
    Function to return prestatiemetingen through Ajax request
    @param request: http request object
    @return: JsonResponse
    """
    project = Project.objects.get(pk=request.GET.get('project_number', None))
    numbers = []
    prestatiemetingen = Prestatiemeting.objects.filter(project=project)
    for pm in prestatiemetingen:
        numbers.append(pm.number)

    data = {
        'numbers': numbers
    }

    return JsonResponse(data)


@login_required
@permission_required('perms.view_forms')
def forms_detail(request, form_id):
    """
    View to show form
    @param request: http request object
    @param form_id: id of the form
    @return: forms view
    """
    form = get_object_or_404(Form, pk=form_id)
    return render(request, 'data/forms_detail.html', {'form': form})


@login_required
@permission_required('perms.view_forms')
def prestatiemeting(request, prestatiemeting_id):
    """
    View to show prestatiemeting form
    @param request: http request object
    @param prestatiemeting_id: prestatiemeting id
    @return: prestatiemeting view
    """
    pm = get_object_or_404(Prestatiemeting, pk=prestatiemeting_id)
    questions = pm.get_questions_og()

    if not pm.is_configured():
        messages.error(request, 'Deze prestatiemeting bevat nog geen configuratie. Configureer de prestatiemeting'
                                ' eerst.')
        return redirect('data:forms')

    if request.POST:
        PrestatiemetingResult.objects.filter(prestatiemeting_id=prestatiemeting_id, question__about='OG').delete()
        print(request.POST)
        for question in questions:
            print(question)
            answer_id = request.POST.get(f'question_{question.number}')
            explanation = None
            if request.POST.get(f'explanation_{question.number}') != "":
                explanation = request.POST.get(f'explanation_{question.number}')

data/templates/data/forms.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% block page_header %}Formulieren{% endblock page_header %}{% endblock title %}

{% block content %}
    {% include 'data/forms_table.html' with forms=forms %}

    <hr>

    <span><h5>Prestatiemeting</h5></span>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 id="search-results-title" class="m-0 font-weight-bold text-primary">Prestatiemeting</h6>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'data:forms' %}">
                {% csrf_token %}
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="project-select">Project:</label>
                    <div class="col-sm-10">
                        <select name="project_select" class="form-control col-6" id="project-select">
                            <option value="">Selecteer project...</option>
                            {% for project in projects %}
                                <option value="{{ project.number }}">{{ project.number }}: {{ project.name }} - {{ project.opdrachtgever }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="pm-select">Prestatiemeting:</label>
                    <div class="col-sm-10">
                        <select name="pm_select" class="form-control col-6" id="pm-select">
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary m-2" name="prestatiemeting_conf">Prestatiemeting configureren</button>
                <button type="submit" class="btn btn-primary m-2" name="prestatiemeting_fill">Prestatiemeting invullen</button>
                <a href="{% url 'data:upload' %}" class="btn btn-primary m-2">Prestatiemeting uploaden</a>
            </form>
        </div>
    </div>
{% endblock content%}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'data/js/data.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
{% endblock %}

data/templates/data/forms_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% block page_header %}Invullen formulier: {{ form.name }}{% endblock page_header %}{% endblock title %}

{% block header_button %}
    <a href="#" data-toggle="modal" data-target="#discardModal" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Terug naar overzicht</a>
{% endblock %}

{% block content %}
    <div class="card mb-4">
        <div class="card-header py-3">
            {{ form.name }}
        </div>
        <div class="card-body">
            <form>
                {% for formfield in form.formfield_set.all %}
                    <div class="form-group">
                        <label for="answer"><b>{{ formfield.text }}</b></label>
                        {% if formfield.formfieldmultiplechoiceanswer_set.all %}
                            {% for answer in formfield.formfieldmultiplechoiceanswer_set.all %}
                                <div class="form-check" id="answer">
                                    <input class="form-check-input" type="radio" name="exampleRadios" id="option{{ forloop.counter }}" value="option{{ answer.id }}">
                                    <label class="form-check-label" for="option{{ forloop.counter }}">
                                        {{ answer }}
                                    </label>
                                </div>
                            {% endfor %}
                        {% else %}
                            <input class="form-control" type="text" id="answer">
                        {% endif %}
                    </div>
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Opslaan</button>
            </form>
        </div>
    </div>
{% endblock content%}

{% block modals %}
  <!-- Discard form Modal-->
  <div class="modal fade" id="discardModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Pagina verlaten zonder op te slaan?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Klik op pagina verlaten als u zeker bent dat u het formulier niet wilt opslaan.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'data:forms' %}">Pagina verlaten</a>
        </div>
      </div>
    </div>
  </div>
{% endblock modals %}

data/templates/data/forms_table.html
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 id="search-results-title" class="m-0 font-weight-bold text-primary">Formulieren</h6>
    </div>
    <div class="card-body" id="replaceable-content">
        <div class="table-responsive">
            <table class="table table-bordered" id="formsTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Naam</th>
                        <th>Omschrijving</th>
                        <th>Laatst ingevuld</th>
                        <th>Actie</th>
                    </tr>
                </thead>
                <tbody>
                    {% for form in forms %}
                        <tr>
                            <td>{{ form.id }}</td>
                            <td>{{ form.name }}</td>
                            <td>{{ form.description }}</td>
                            <td>{{ form.last_filled }}</td>
                            <td><a class="btn btn-primary btn-sm" href="{% url 'data:forms_detail' form.id %}">Invullen</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

data/templates/data/prestatiemeting.html
{% extends "base.html" %}

{% block title %}{% block page_header %}Prestatiemeting voor project {{ prestatiemeting.project }}{% endblock page_header %}{% endblock title %}

{% block header_button %}
    <a href="#" data-toggle="modal" data-target="#exportModal" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Download Excel formulier</a>
{% endblock %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% if prestatiemeting.get_questions_og %}
        <form method="post" action="{% url 'data:prestatiemeting' prestatiemeting.id %}">
            {% csrf_token %}
            {% for theme in prestatiemeting.get_distinct_themes_og %}
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 id="search-results-title" class="m-0 font-weight-bold text-primary">{{ theme }}</h6>
                    </div>
                    <div class="card-body">
                        {% for question in prestatiemeting.get_questions_og %}
                            {% if question.theme == theme %}
                                <fieldset class="form-group">
                                    <label for="answer"><b>{{ question.number }}. {{ question.question }}</b></label>
                                    {% for answer in question.prestatiemetinganswer_set.all %}
                                        <div class="form-check" id="answer">
                                            <input class="form-check-input" type="radio" name="question_{{ question.number }}" id="option{{ answer.id }}" value="{{ answer.id }}" required>
                                            <label class="form-check-label" for="option{{ answer.id }}">
                                                {{ answer.gradation.letter }}. {{ answer.gradation.description }}: {{ answer.answer }}
                                            </label>
                                        </div>
                                    {% endfor %}
                                    <textarea class="form-control mt-2" id="explanation_{{ question.number }}" name="explanation_{{ question.number }}" placeholder="Type uw opmerkingen hier..."></textarea>
                                </fieldset>
                                <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <div class="card shadow mb-4">
                <button type="submit" class="btn btn-primary">Opslaan</button>
            </div>
        </form>
    {% endif %}
{% endblock content%}

{% block modals %}
  <!-- Discard form Modal-->
  <div class="modal fade" id="exportModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Excel formulier downloaden?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Hier kunt u het bijbehorende formulier OG -> ON downloaden</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Sluiten</button>
          <a class="btn btn-primary" href="{% url 'data:export_excel' prestatiemeting.id %}">Downloaden</a>
        </div>
      </div>
    </div>
  </div>
{% endblock modals %}

data/templates/data/projects.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% block page_header %}Projecten{% endblock page_header %}{% endblock title %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 id="search-results-title" class="m-0 font-weight-bold text-primary">Projecten</h6>
        </div>
        <div class="card-body" id="replaceable-content">
            <div class="table-responsive">
                <table class="table table-bordered" id="formsTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Nummer</th>
                            <th>Naam</th>
                            <th>Omschrijving</th>
                            <th>Opdrachtgever</th>
                            <th>Actie</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td>{{ project.pk }}</td>
                                <td>{{ project.name }}</td>
                                <td>{{ project.description }}</td>
                                <td>{{ project.opdrachtgever }}</td>
                                <td><a class="btn btn-primary btn-sm" href="{% url 'dashboard:project_dashboard' project.encode_number %}">Naar dashboard</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content%}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'data/js/data.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
{% endblock %}

data/templates/data/upload.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% block page_header %}Upload Data{% endblock page_header %}{% endblock title %}

{% block content %}

    <div class="card mb-4">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="source">Selecteer databron</label>
                        <select class="form-control col-3" id="source" name="source" required>
                            <option value="">Selecteer bron</option>
                            <option value="prestatiemeting">Prestatiemeting</option>
                            <option value="ultimo">Ultimo</option>
                            <option value="sap">Sap</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="fileUpload">Upload databestand</label>
                        <input class="form-control-file" type="file" name="datafile" id="fileUpload" required />
                    </div>
                <button type="submit" class="btn btn-primary">Upload</button>
            </form>
        </div>
    </div>

{% endblock %}