bvp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('vpi/', include('vpi.urls')),
    path('data/', include('data.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout, name='logout')
]

dashboard/urls.py
from django.urls import path

import data.views as dataviews
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('<int:dashboard_id>', views.general_dashboard, name='dashboard'),
    path('project/<project_number>', views.project_dashboard, name='project_dashboard'),
    path('reports', views.reports, name='reports'),
    path('report', views.reports_detail, name='report'),
    path('ajax/get_pms', dataviews.get_prestatiemetingen, name='get_prestatiemetingen')
]

vpi/urls.py
from django.urls import path

from . import views


app_name = 'vpi'
urlpatterns = [
    path('', views.search, name='index'),
    path('<int:vpi_id>/', views.details, name='detail'),
]

dashboard/models.py
import abc

from django.db import models
from model_utils.managers import InheritanceManager

from data.models.project import Project
from vpi import vpis
from vpi.models import VPI


class Dashboard(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        if self.project:
            return f'{self.project.number}: {self.project.name}'
        else:
            return self.name

    def get_ordered_objects(self):
        """
        Return dashboard objects ordered by row number and row order
        @return: Queryset of DashboardObjects
        """
        return self.objects.order_by('row_number', 'row_order').filter(dashboard=self)

    def get_ordered_objects_by_row(self):
        """
        Returns DashboardObjects divided into a list per row
        @return: List of Querysets
        """
        row_amount = DashboardObject.objects.values('row_number').filter(dashboard=self).distinct().count()

        object_rows = []

        for row_number in range(1, row_amount + 1):
            object_rows.append(DashboardObject.objects.filter(dashboard=self, row_number=row_number).order_by('row_order'))

        return object_rows


class DashboardObject(models.Model):
    AREA = 'area'
    CARD = 'card'
    BAR = 'bar'
    PIE = 'pie'
    TABLE = 'table'
    PROGRESS = 'progress'
    CHART_CHOICES = [
        (AREA, 'Area chart'),
        (CARD, 'Card'),
        (BAR, 'Bar chart'),
        (PIE, 'Pie chart'),
        (TABLE, 'Table'),
        (PROGRESS, 'Progress')
    ]

    dashboard = models.ForeignKey(Dashboard, on_delete=models.CASCADE)
    vpi = models.ForeignKey(to='vpi.VPI', on_delete=models.CASCADE)
    chart_type = models.CharField(max_length=10, choices=CHART_CHOICES)
    col_width = models.IntegerField()
    row_number = models.IntegerField()
    row_order = models.IntegerField()
    vpi_data = None

    class Meta(object):
        unique_together = (('dashboard', 'row_number', 'row_order'),)

    @property
    def filters(self):
        """
        Return collection of filters in a dictionary format
        @return: Dict with filters
        """
        filter_dict = {}
        if self.dashboard.project:
            filter_dict['project'] = self.dashboard.project
        filters = FilterObject.objects.filter(dashboard_object=self).select_subclasses()
        for filter_object in filters:
            filter_dict[filter_object.filter_by] = filter_object.filter_value

        return filter_dict

    def get_vpi_data(self):
        """
        Return data for vpi's included in this dashboard
        @return: VPI data in either a dictionary or float format.
        """
        if not self.vpi_data:
            if self.vpi.function:
                self.vpi_data = getattr(vpis, f'{self.vpi.function}')(self.dashboard.project)

        return self.vpi_data

    def get_vpi_target_color(self):
        """
        Returns the target color of a vpi value.
        @return: bootstrap color (danger/warning/success)
        """
        vpi_value = self.get_vpi_data()
        if not vpi_value is None:
            vpi_target = self.vpi.get_target(self.dashboard.project)
            upper_limit = vpi_target.upper_limit
            lower_limit = vpi_target.lower_limit

            if lower_limit <= vpi_value <= upper_limit:
                return 'warning'
            elif vpi_target.is_better == 'higher':
                if vpi_value > upper_limit:
                    return 'success'
                else:
                    return 'danger'
            elif vpi_target.is_better == 'lower':
                if vpi_value < lower_limit:
                    return 'success'
                else:
                    return 'danger'


class Report(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(null=True, blank=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)

dashboard/views.py
from django.contrib.admin.utils import unquote
from django.contrib.auth.decorators import permission_required, login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from data.helpers.excel import prestatiemeting_report
from data.models.prestatiemeting import Prestatiemeting, PrestatiemetingResult, PrestatiemetingQuestion
from data.models.project import Project
from vpi.models import VPI, VPIValue
from .models import Report, Dashboard, DashboardObject


@login_required
@permission_required('perms.view_dashboard', login_url='login')
def general_dashboard(request, dashboard_id):
    """
    A general dashboard view defined in the database.
    @param request: http request object
    @param dashboard_id: id of the dashboard to be shown.
    @return: dashboard view
    """
    dashboard = get_object_or_404(Dashboard, id=dashboard_id)
    print(VPIValue.objects.select_subclasses())
    return render(request, 'dashboard/dashboard.html', {'dashboard': dashboard})


@login_required
@permission_required('perms.view_dashboard', login_url='login')
def project_dashboard(request, project_number):
    """
    Dashboard view for specific projects
    @param request: http request object
    @param project_number: id of the project.
    @return: dashboard view
    """
    project_number = unquote(project_number)
    dashboard, created = Dashboard.objects.get_or_create(project_id=project_number,
                                                         defaults={'name': f'autogenerated {project_number}'})

    # Add some default dashboard objects to newly created dashboard
    if created:
        DashboardObject.objects.get_or_create(dashboard=dashboard, vpi_id=1, chart_type=DashboardObject.CARD,
                                              col_width=3, row_number=1, row_order=1)
        DashboardObject.objects.get_or_create(dashboard=dashboard, vpi_id=13, chart_type=DashboardObject.PIE,
                                              col_width=4, row_number=2, row_order=1)

    return render(request, 'dashboard/dashboard.html', {'dashboard': dashboard})


@login_required
@permission_required('perms.generate_reports')
def reports(request):
    """
    Overview view of available reports
    @param request: http request object
    @return: reports view
    """
    reports = Report.objects.all()
    projects = Project.objects.all()

    return render(request, 'dashboard/reports.html', {'reports': reports,
                                                      'projects': projects})


@login_required
@permission_required('perms.generate_reports')
def reports_detail(request):
    """
    Detail view for individual reports
    @param request: http request object
    @return: detail report view
    """
    if request.POST:
        pm = Prestatiemeting.objects.get(project_id=request.POST.get('project_select'),
                                         number=request.POST.get('pm_select'))

        output = prestatiemeting_report(pm.id)
        output.seek(0)

        filename = 'prestatiemeting_resultaten.xlsx'
        response = HttpResponse(
            output,
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = 'attachment; filename=%s' % filename

        return response

dashboard/templates/dashboard/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}{% block title %}Dashboard - {{ dashboard }}{% endblock title %}{% endblock page_header %}

{% block content %}
    {% for row in dashboard.get_ordered_objects_by_row %}
        <div class="row">
            {% for object in row %}
                {% if object.chart_type == object.CARD %}
                    {% include 'dashboard/objects/card.html' with object=object %}
                {% elif object.chart_type == object.BAR %}
                    {% include 'dashboard/objects/bar.html' with object=object %}
                {% elif object.chart_type == object.TABLE %}
                    {% include 'dashboard/objects/table.html' with object=object %}
                {% elif object.chart_type == object.PIE %}
                    {% include 'dashboard/objects/pie.html' with object=object %}
                {% elif object.chart_type == object.PROGRESS %}
                    {% include 'dashboard/objects/progress.html' with object=object %}
                {% endif %}
            {% endfor %}
         </div>
    {% endfor %}
{% endblock content %}

dashboard/templates/dashboard/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Dashboard{% endblock title %}

{% block page_header %}Dashboard{% endblock page_header %}
{% block content %}
  <!-- Content Row -->
  <div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Earnings (Monthly)</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
            </div>
            <div class="col-auto">
              <i class="fas fa-calendar fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-success shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Earnings (Annual)</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
            </div>
            <div class="col-auto">
              <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks</div>
              <div class="row no-gutters align-items-center">
                <div class="col-auto">
                  <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                </div>
                <div class="col">
                  <div class="progress progress-sm mr-2">
                    <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-warning shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Pending Requests</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
            </div>
            <div class="col-auto">
              <i class="fas fa-comments fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Content Row -->

  <div class="row">

    <!-- Area Chart -->
    <div class="col-xl-8 col-lg-7">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Earnings Overview</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
              <div class="dropdown-header">Dropdown Header:</div>
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="chart-area">
            <canvas id="myAreaChart"></canvas>
          </div>
        </div>
      </div>
    </div>

    <!-- Pie Chart -->
    <div class="col-xl-4 col-lg-5">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Revenue Sources</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
              <div class="dropdown-header">Dropdown Header:</div>
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="chart-pie pt-4 pb-2">
            <canvas id="myPieChart"></canvas>
          </div>
          <div class="mt-4 text-center small">
            <span class="mr-2">
              <i class="fas fa-circle text-primary"></i> Direct
            </span>
            <span class="mr-2">
              <i class="fas fa-circle text-success"></i> Social
            </span>
            <span class="mr-2">
              <i class="fas fa-circle text-info"></i> Referral
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Content Row -->
  <div class="row">

    <!-- Content Column -->
    <div class="col-lg-6 mb-4">

      <!-- Project Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Projects</h6>
        </div>
        <div class="card-body">
          <h4 class="small font-weight-bold">Server Migration <span class="float-right">20%</span></h4>
          <div class="progress mb-4">
            <div class="progress-bar bg-danger" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <h4 class="small font-weight-bold">Sales Tracking <span class="float-right">40%</span></h4>
          <div class="progress mb-4">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <h4 class="small font-weight-bold">Customer Database <span class="float-right">60%</span></h4>
          <div class="progress mb-4">
            <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <h4 class="small font-weight-bold">Payout Details <span class="float-right">80%</span></h4>
          <div class="progress mb-4">
            <div class="progress-bar bg-info" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <h4 class="small font-weight-bold">Account Setup <span class="float-right">Complete!</span></h4>
          <div class="progress">
            <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>
      </div>

      <!-- Color System -->
      <div class="row">
        <div class="col-lg-6 mb-4">
          <div class="card bg-primary text-white shadow">
            <div class="card-body">
              Primary
              <div class="text-white-50 small">#4e73df</div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 mb-4">
          <div class="card bg-success text-white shadow">
            <div class="card-body">
              Success
              <div class="text-white-50 small">#1cc88a</div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 mb-4">
          <div class="card bg-info text-white shadow">
            <div class="card-body">
              Info
              <div class="text-white-50 small">#36b9cc</div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 mb-4">
          <div class="card bg-warning text-white shadow">
            <div class="card-body">
              Warning
              <div class="text-white-50 small">#f6c23e</div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 mb-4">
          <div class="card bg-danger text-white shadow">
            <div class="card-body">
              Danger
              <div class="text-white-50 small">#e74a3b</div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 mb-4">
          <div class="card bg-secondary text-white shadow">
            <div class="card-body">
              Secondary
              <div class="text-white-50 small">#858796</div>
            </div>
          </div>
        </div>
      </div>

    </div>

    <div class="col-lg-6 mb-4">

      <!-- Illustrations -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Illustrations</h6>
        </div>
        <div class="card-body">
          <div class="text-center">
            <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="{% static 'img/undraw_posting_photo.svg' %}" alt="">
          </div>
          <p>Add some quality, svg illustrations to your project courtesy of <a target="_blank" rel="nofollow" href="https://undraw.co/">unDraw</a>, a constantly updated collection of beautiful svg images that you can use completely free and without attribution!</p>
          <a target="_blank" rel="nofollow" href="https://undraw.co/">Browse Illustrations on unDraw &rarr;</a>
        </div>
      </div>

      <!-- Approach -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Development Approach</h6>
        </div>
        <div class="card-body">
          <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce CSS bloat and poor page performance. Custom CSS classes are used to create custom components and custom utility classes.</p>
          <p class="mb-0">Before working with this theme, you should become familiar with the Bootstrap framework, especially the utility classes.</p>
        </div>
      </div>

    </div>
  </div>
{% endblock content %}

{% block scripts %}
  {{ block.super }}
  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
{% endblock %}

dashboard/templates/dashboard/report.html
{% extends "base.html" %}

{% block title %}{% block page_header %}Report {{ report.name }}{% endblock page_header %}{% endblock title %}

{% block content %}
{% endblock content%}

dashboard/templates/dashboard/reports.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% block page_header %}Rapportages{% endblock page_header %}{% endblock title %}

{% block content %}
    <div class="col-6 mx-auto">
        <div class="card">
            <div class="card-header">
                Prestatiemetingen
            </div>
            <div class="card-body">
                <form class="form-inline" method="post" action="{% url 'dashboard:report' %}">
                    {% csrf_token %}
                    <select name="project_select" class="form-control col-5 mr-4" id="project-select">
                        <option value="">Selecteer project...</option>
                        {% for project in projects %}
                            <option value="{{ project.number }}">{{ project.number }}: {{ project.name }} - {{ project.opdrachtgever }}</option>
                        {% endfor %}
                    </select>
                    <select name="pm_select" class="form-control col-3 mr-4" id="pm-select">
                    </select>
                    <button type="submit" class="btn btn-primary">Download</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content%}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'dashboard/js/dashboard.js' %}"></script>
{% endblock %}

dashboard/templates/dashboard/vpi_dashboard.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% block page_header %}{{ vpi.name }}{% endblock page_header %}{% endblock title %}

{% block header_button %}
    <a href="{% url 'vpi:index' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Terug naar overzicht</a>
{% endblock %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="row">
        <div class="col-6">
            <div class="card shadow mb-4">
                <div class="card-header">
                    <p class="card-text">{{ vpi.name }}</p>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ vpi.description }}</p>
                    <p class="card-text">Gemeten in: <b>{{ vpi.measuring_unit }}</b></p>
                </div>
            </div>
        </div>
    </div>


    <!-- Earnings (Monthly) Card Example -->
    <div class="row">
        <div class="col-xl-3 col-md-6 mb-4">
          <div class="card border-left-{{ vpi.get_target_color }} shadow h-100 py-2">
            <div class="card-body">
              <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-{{ vpi.get_target_color }} text-uppercase mb-1">{{ vpi.name}}</div>
                  <div class="h5 mb-0 font-weight-bold text-gray-800">{{ vpi.get_value|floatformat:1 }} {{ vpi.measuring_unit }}</div>
                </div>
                <div class="col-auto">
                  <i class="fas fa-calendar fa-2x text-gray-300"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>

    <!-- Area Chart -->
    <div class="row">
        <div class="col-xl-8 col-lg-7">
          <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
              <h6 class="m-0 font-weight-bold text-primary">Historisch verloop</h6>
              <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                  <div class="dropdown-header">Dropdown Header:</div>
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
              <div class="chart-area">
                <canvas id="myAreaChart"></canvas>
              </div>
            </div>
          </div>
        </div>
    </div>


{% endblock content%}

{% block scripts %}
  {{ block.super }}
  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
{% endblock %}