bvp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('vpi/', include('vpi.urls')),
    path('data/', include('data.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout, name='logout')
]

dashboard/urls.py
from django.urls import path

import data.views as dataviews
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('<int:dashboard_id>', views.general_dashboard, name='dashboard'),
    path('project/<project_number>', views.project_dashboard, name='project_dashboard'),
    path('reports', views.reports, name='reports'),
    path('report', views.reports_detail, name='report'),
    path('ajax/get_pms', dataviews.get_prestatiemetingen, name='get_prestatiemetingen')
]

data/urls.py
from django.urls import path

from . import views

app_name = 'data'
urlpatterns = [
    path('upload', views.upload, name='upload'),
    path('forms', views.forms, name='forms'),
    path('forms/<int:form_id>', views.forms_detail, name='forms_detail'),
    path('projects', views.projects_view, name='projects'),
    path('prestatiemeting/<int:prestatiemeting_id>/', views.prestatiemeting, name='prestatiemeting'),
    path('prestatiemeting/<int:prestatiemeting_id>/config/', views.prestatiemeting_config, name='prestatiemeting_config'),
    path('prestatiemeting/<int:prestatiemeting_id>/export/', views.export_excel, name='export_excel'),
    path('ajax/get_pms', views.get_prestatiemetingen, name='get_prestatiemetingen'),
]

vpi/urls.py
from django.urls import path

from . import views


app_name = 'vpi'
urlpatterns = [
    path('', views.search, name='index'),
    path('<int:vpi_id>/', views.details, name='detail'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock title %} | Istimewa BVP</title>

  {% include 'favicon.html' %}

  {% block stylesheets %}

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
{#  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">#}

  <!-- Bootstrap css -->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/scss/bootstrap.scss' %}">

  <!-- Custom styles for this template-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/sb-admin-2.css' %}">

  <!-- Stylesheet for datatables -->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

  <!-- Custom css to modify template -->
  <link href="{% static 'style.css' %}" rel="stylesheet">

  {% endblock stylesheets %}

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index' %}">
        <div class="sidebar-brand-text mx-3">Istimewa <sup>BVP</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'dashboard:dashboard' 2 %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Nav Item - performance indicators -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'vpi:index' %}">
          <i class="fas fa-fw fa-file-alt"></i>
          <span>Zoek VPI's</span></a>
      </li>

      <!-- Nav Item - reporting -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:reports' %}">
          <i class="fas fa-fw fa-cogs"></i>
          <span>Rapportages</span></a>
      </li>

       <!-- Nav Item - reporting -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'data:projects' %}">
          <i class="fas fa-fw fa-cogs"></i>
          <span>Projecten</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">
      
      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-file-alt"></i>
          <span>Data invoeren</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">invoer methoden:</h6>
            <a class="collapse-item" href="{% url 'data:forms' %}">Formulieren</a>
            <a class="collapse-item" href="{% url 'data:upload' %}">Databestanden</a>
            <a class="collapse-item" href="{% url 'data:forms' %}">Prestatiemeting</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">
      
       <!-- Nav Item - reporting -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">
          <i class="fas fa-fw fa-cogs"></i>
          <span>Beheren</span></a>
      </li>


      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-3 d-none d-lg-inline text-gray-600 small">{{ user.get_full_name }}</span>
                <i class="fas fa-user fa-lg"></i>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->


        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">{% block page_header %}{% endblock page_header %}</h1>
            {% block header_button %}<a href="{% url 'dashboard:reports' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>{% endblock %}
          </div>


          <!-- Message section -->
          {% if messages %}
            {% for message in messages %}
                <div id="message-box" {% if message.tags %} class="card bg-{{ message.tags }} text-white shadow mb-4 p-1 pl-3"{% endif %}>
                    <div class="message">
                        {{ message }}
                    </div>
{#                        <button class="close float-right" type="button" onclick="remove_message()">#}
{#                            <span aria-hidden="true">x</span>#}
{#                        </button>#}
                </div>
            {% endfor %}
          {% endif %}

          {% block content %}
          {% endblock content %}

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Istimewa Elektro 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  {% block modals %}{% endblock modals %}

  {% block scripts %}

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <script>
    function remove_message() {
    // Removes an element from the document
    var element = document.getElementById('message-box');
    element.remove()
}
  </script>

  {% endblock scripts %}

</body>

</html>

templates/favicon.html
{% load static %}

<link rel="apple-touch-icon" sizes="57x57" href="{%  static 'img/favicon/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{%  static 'img/favicon/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{%  static 'img/favicon/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{%  static 'img/favicon/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{%  static 'img/favicon/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{%  static 'img/favicon/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{%  static 'img/favicon/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{%  static 'img/favicon/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{%  static 'img/favicon/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{%  static 'img/favicon/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{%  static 'img/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{%  static 'img/favicon/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{%  static 'img/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'img/favicon/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

templates/forgot-password.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Forgot Password</title>

  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                    <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
                  </div>
                  <form class="user">
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <a href="login.html" class="btn btn-primary btn-user btn-block">
                      Reset Password
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="login.html">Already have an account? Login!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% block page_header %}Homepage{% endblock page_header %}{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card shadow mb-4">
                <div class="card-header">
                    Toelichting applicatie
                </div>
                <div class="card-body">
                    <p>
                        Deze applicatie is ontwikkeld in opdracht van Istimewa. Het doel is om het verzamelen van data en het zoeken van prestatie indicatoren te automatiseren.
                    </p>
                    <p class="mb-0">
                        De applicatie is opgebouwd in Python met behulp van het Django framework. Voor de insterface is gebruik gemaakt van het SB Admin 2 template.
                    </p>
                </div>
            </div>
                <div class="card shadow mb-4">
                    <div class="card-header">
                        Prestatiemeten
                    </div>
                <div class="card-body">
                    <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" src="static/img/prestatiemeting.png">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card shadow mb-4">
                <div class="card-header">
                    Applicatie context
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" src="static/img/project_overview.png">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Login | Istimewa BVP</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{%  static 'css/sb-admin-2.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">



  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block" style="background: url('{% static 'img/background_8.jpg' %}')"></div>
                <div class="col-lg-6">
                  <div class="p-5">
                    {% if form.errors %}
                      <p>Uw gebruikersnaam en/of wachtwoord is niet correct.</p>
                    {% endif %}
                    {% if next %}
                      {% if user.is_authenticated %}
                        <p>Uw account heeft geen toegang to deze pagina. Neem contact op met blablabla als dit niet klopt.</p>
                      {% else %}
                        <p>Please login to see this page.</p>
                      {% endif %}
                    {% endif %}
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Log in</h1>
                  </div>
                  <form method="post" action="{% url 'login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                      <input name="username" type="text" autofocus autocapitalize="none"
                           autocomplete="off" maxlength="150" required id="id_username"
                           class="form-control form-control-user" aria-describedby="emailHelp"
                           placeholder="Gebruikersnaam">
                    </div>
                    <div class="form-group">
                      <input name="password" type="password" autocomplete="off" required
                           id="id_password" class="form-control form-control-user" placeholder="Wachtwoord">
                    </div>
                  <input type="submit" value="Log in" class="btn btn-primary btn-user btn-block">
                  <input type="hidden" name="next" value="{{ next }}">
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Wachtwoord vergeten?</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/template.html
{% extends "base.html" %}

{% block title %}{% block page_header %}{% endblock page_header %}{% endblock title %}

{% block content %}    
{% endblock content%}