bvp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('vpi/', include('vpi.urls')),
    path('data/', include('data.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout, name='logout')
]

vpi/urls.py
from django.urls import path

from . import views


app_name = 'vpi'
urlpatterns = [
    path('', views.search, name='index'),
    path('<int:vpi_id>/', views.details, name='detail'),
]

vpi/models.py
from enum import Enum

from django.contrib.contenttypes.models import ContentType
from django.db import models
from model_utils.managers import InheritanceManager

from data.models.other import DataContainer
from data.models.prestatiemeting import Prestatiemeting
from vpi import vpis


class VPIAction(Enum):
    AVG = 'average'
    HIGH = 'highest'
    LOW = 'lowest'
    SUM = 'total'


class VPIInterval(Enum):
    DAY = 'day'
    MONTH = 'month'
    YEAR = 'year'
    NONE = 'none'


class VPISource(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    model_name = models.CharField(max_length=100)
    datefield = models.CharField(max_length=100)
    projectfield = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name


class VPI(models.Model):
    name = models.CharField(max_length=100)
    question = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    measuring_unit = models.CharField(max_length=20, blank=True)
    function = models.CharField(max_length=30, null=True, blank=True)
    has_subset = models.BooleanField(default=False)
    decimal_amount = models.IntegerField(default=2)
    source = models.ForeignKey(VPISource, on_delete=models.CASCADE)
    type = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f'{self.name}'

    @property
    def detail_config(self):
        return self.vpidetailconfig

    def get_value(self, project):
        """
        Generic function which calls the related vpi function, returning the values for this specific vpi. Returns
        cached data if available.
        @param filters: (optional) filters
        @return: data can be dictionary or float
        """
        if self.function:
            return getattr(vpis, f'{self.function}')(project)

    def get_target(self, project=None):
        """
        Returns the targat which is set for a vpi in de database
        @param project: (optional) get target for specific project
        @return: VPITarget object
        """
        try:
            return self.vpitarget_set.get(project=project)
        except VPITarget.DoesNotExist:
            return self.vpitarget_set.get()
        except VPITarget.DoesNotExist:
            return None

    def get_color(self, value):
        """
        Get color to reflect the status of a VPI
        @param value: value for VPI
        @return: color ('danger'/'warning'/'success')
        """
        target = self.vpitarget_set.get(project__isnull=True)
        upper_limit = target.upper_limit
        lower_limit = target.lower_limit

        if lower_limit <= value <= upper_limit:
            return 'warning'
        elif target.is_better == 'higher':
            if value > upper_limit:
                return 'success'
            else:
                return 'danger'
        elif target.is_better == 'lower':
            if value < lower_limit:
                return 'success'
            else:
                return 'danger'


class VPIValue(models.Model):
    vpi = models.ForeignKey(VPI, on_delete=models.CASCADE)
    happened = models.DateTimeField()
    created = models.DateTimeField(auto_now_add=True)
    project_number = models.CharField(max_length=8, null=True, blank=True)
    objects = InheritanceManager()


class VPIValueNumber(VPIValue):
    value = models.FloatField()


class VPIValueList(VPIValue):
    @property
    def value(self):
        return list(self.listvalue_set.values_list('value', flat=True))

    @value.setter
    def value(self, value_list):
        for item in value_list:
            ListValue(list=self, value=item).save()


class ListValue(models.Model):
    list = models.ForeignKey(VPIValueList, on_delete=models.CASCADE)
    value = models.FloatField()


class VPIValuePrestatiemeting(VPIValue):
    prestatiemeting = models.ForeignKey(Prestatiemeting, on_delete=models.CASCADE)

    @property
    def value(self):
        return self.prestatiemeting.prestatiemetingresult_set.all()

    @value.setter
    def value(self, prestatiemeting):
        self.prestatiemeting = prestatiemeting


class VPIData:
    # list of strings
    datetimes = []

    # list or nested lists. e.g. [1, 2, 3, 4] or [[1, 2, 3, 4],[5, 6, 7, 8]]
    data = []

    def __init__(self, data, labels):
        self.data = data
        self.datetimes = labels


class VPIDetailConfig(models.Model):
    LINE = 'line'
    BAR = 'bar'

    CHART_CHOICES = [
        (LINE, 'Line chart'),
        (BAR, 'Bar chart'),
    ]

    vpi = models.OneToOneField(VPI, on_delete=models.CASCADE)
    available_filters = models.CharField(max_length=10)
    chart_type = models.CharField(max_length=10, choices=CHART_CHOICES)


class VPITarget(models.Model):
    LOWER = 'lower'
    HIGHER = 'higher'
    CHOICES = [
        (LOWER, 'Lager is beter'),
        (HIGHER, 'Hoger is better')
    ]
    vpi = models.ForeignKey(to='vpi.VPI', on_delete=models.CASCADE)
    lower_limit = models.FloatField()
    upper_limit = models.FloatField()
    is_better = models.CharField(max_length=6, choices=CHOICES)
    project = models.ForeignKey(to='data.Project', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        if self.project:
            return f'{str(self.project)}'
        else:
            return f'VPI: {str(self.vpi)}'


class VPIDetailObject(models.Model):
    AREA = 'area'
    CARD = 'card'
    BAR = 'bar'
    PIE = 'pie'
    TABLE = 'table'
    PROGRESS = 'progress'
    CHART_CHOICES = [
        (AREA, 'Area chart'),
        (CARD, 'Card'),
        (BAR, 'Bar chart'),
        (PIE, 'Pie chart'),
        (TABLE, 'Table'),
        (PROGRESS, 'Progress')
    ]

    vpi = models.ForeignKey(to='vpi.VPI', on_delete=models.CASCADE)
    chart_type = models.CharField(max_length=10, choices=CHART_CHOICES)
    width = models.IntegerField()
    _data = None

    @property
    def filters(self):
        """
        Return collection of filters in a dictionary format
        @return: Dict with filters
        """
        filter_dict = {}
        filters = FilterObject.objects.filter(vpi_detail_object=self).select_subclasses()
        for filter_object in filters:
            filter_dict[filter_object.filter_by] = filter_object.filter_value

        return filter_dict

    def get_data_test(self):
        container = DataContainer(self.vpi.source.model_name)
        container.apply_filters(self.filters)
        return container

    @property
    def targets(self):
        return self.vpi.vpitarget_set.all()

    @property
    def vpi_data(self):
        """
        Return data for vpi's included in this dashboard
        @return: VPI data in either a dictionary or float format.
        """
        if not self._data:
            self._data = self.vpi.get_value(self.filters)

        return self._data


class FilterObject(models.Model):
    vpi_detail_object = models.ForeignKey(VPIDetailObject, on_delete=models.CASCADE)
    filter_by = models.CharField(max_length=100)
    filter_value = None
    objects = InheritanceManager()


class FilterObjectBoolean(FilterObject):
    filter_value = models.BooleanField()


class FilterObjectString(FilterObject):
    filter_value = models.CharField(max_length=100)


class FilterObjectDateTime(FilterObject):
    filter_value = models.DateTimeField()

vpi/views.py
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, Http404
from django.template.loader import render_to_string
from django.views import generic

from data.models.project import Project
from .models import VPI, FilterObjectDateTime, FilterObjectString, VPIDetailObject


def index(request):
    return render(request, 'vpi/index.html')


@login_required
@permission_required('perms.view_dashboard')
def search(request):
    """
    Page on which VPI's are shown and can be searched
    @param request: http request object
    @return: VPI search view
    """
    ctx = {}
    url_parameter = request.GET.get("q")

    if url_parameter:
        vpis = VPI.objects.filter(name__icontains=url_parameter)
    else:
        vpis = VPI.objects.all()

    ctx["vpis"] = vpis
    if request.is_ajax():

        html = render_to_string(
            template_name="vpi/vpi-results-partial.html", context={"vpis": vpis}
        )
        data_dict = {"html_from_view": html}
        return JsonResponse(data=data_dict, safe=False)

    return render(request, "vpi/search.html", context=ctx)


def details(request, vpi_id):
    """
    Detail page for individual VPIs
    @param request: http request object
    @param vpi_id: VPI id
    @return: VPI detail view
    """
    projects = Project.objects.all()
    vpi = VPI.objects.get(pk=vpi_id)

    try:
        vpi_detail_object = vpi.vpidetailobject_set.get()
    except VPIDetailObject.DoesNotExist:
        raise Http404

    data_container = vpi_detail_object.get_data_test()

    data = []

    for result in data_container.data:
        data.append(result.get_results())

    if request.POST:
        print(request.POST.get('date-from'))
        print(request.POST.get('date-to'))
        print(request.POST.get('project-select'))

    context = {
        'projects': projects,
        'vpi': vpi,
        'data': data
    }
    return render(request, 'vpi/detail_prestatiemeting.html', context=context)

vpi/templates/vpi/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% block page_header %}{{ vpi.name }}{% endblock page_header %}{% endblock title %}

{% block header_button %}
    <a href="{% url 'vpi:index' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Terug naar overzicht</a>
{% endblock %}

{% block content %}
    {% include 'vpi/objects/card_deck.html' with data=data vpi=vpi %}
    <div class="card-deck">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">VPI omschrijving</h6>
            </div>
            <div class="card-body">
                <p class="card-text">{{ vpi.description }}</p>
                <p class="card-text">
                    {% if vpi.measuring_unit %}
                        Gemeten in: <b>{{ vpi.measuring_unit }}</b>
                    {% endif %}
                </p>
            </div>
        </div>

        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Doelstelling</h6>
            </div>
            <div class="card-body">
                <table class="table table-sm mb-0">
                    <thead>
                        <tr>
                            <th>Project</th>
                            <th>Groen</th>
                            <th>Geel</th>
                            <th>Rood</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for target in vpi.vpitarget_set.all %}
                            <tr>
                                {% if target.project %}
                                    <td>{{ target.project }}</td>
                                {% else %}
                                    <td>Algemeen</td>
                                {% endif %}
                                {% if target.is_better == 'higher' %}
                                    <td>&gt {{ target.upper_limit }}</td>
                                    <td>{{ target.lower_limit }} - {{ target.upper_limit }}</td>
                                    <td>&lt {{ target.lower_limit }}</td>
                                {% elif target.is_better == 'lower' %}
                                    <td>&lt {{ target.lower_limit }}</td>
                                    <td>{{ target.lower_limit }} - {{ target.upper_limit }}</td>
                                    <td>&gt {{ target.upper_limit }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% include 'vpi/objects/line.html' with data=data %}
{% endblock content%}

vpi/templates/vpi/detail_prestatiemeting.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% block page_header %}{{ vpi.name }}{% endblock page_header %}{% endblock title %}

{% block header_button %}
    <a href="{% url 'vpi:index' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Terug naar overzicht</a>
{% endblock %}

{% block content %}
    {% include 'vpi/objects/card_deck.html' with data=data vpi=vpi %}
    <div class="card-deck">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">VPI omschrijving</h6>
            </div>
            <div class="card-body">
                <p class="card-text">{{ vpi.description }}</p>
                <p class="card-text">
                    {% if vpi.measuring_unit %}
                        Gemeten in: <b>{{ vpi.measuring_unit }}</b>
                    {% endif %}
                </p>
            </div>
        </div>

        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Doelstelling</h6>
            </div>
            <div class="card-body">
                <table class="table table-sm mb-0">
                    <thead>
                        <tr>
                            <th>Project</th>
                            <th>Groen</th>
                            <th>Geel</th>
                            <th>Rood</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for target in vpi.vpitarget_set.all %}
                            <tr>
                                {% if target.project %}
                                    <td>{{ target.project }}</td>
                                {% else %}
                                    <td>Algemeen</td>
                                {% endif %}
                                {% if target.is_better == 'higher' %}
                                    <td>&gt {{ target.upper_limit }}</td>
                                    <td>{{ target.lower_limit }} - {{ target.upper_limit }}</td>
                                    <td>&lt {{ target.lower_limit }}</td>
                                {% elif target.is_better == 'lower' %}
                                    <td>&lt {{ target.lower_limit }}</td>
                                    <td>{{ target.lower_limit }} - {{ target.upper_limit }}</td>
                                    <td>&gt {{ target.upper_limit }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% include 'vpi/objects/line.html' with data=data %}
{% endblock content%}

vpi/templates/vpi/index.html
{% extends "base.html" %}

{% block title %}{% block page_header %}Zoek VPI's{% endblock page_header %}{% endblock title %}

{% block content %}    
{% endblock content%}

vpi/templates/vpi/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% block page_header %}Zoek VPI's{% endblock page_header %}{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    <!-- Custom styles for this page -->
    <link href="{% static "vpi/main.css" %}" rel="stylesheet" media="screen">
{% endblock stylesheets %}

{% block content %}
    <div class="card shadow mb-4">
        <div class="card-body">
            <form class="form-inline">
                <label for="category-select">
                    <i id="search-icon" class="fas fa-search fa-lg mr-2" aria-hidden="true"></i>
                </label>
                <select class="form-control mr-2 col-3" id="category-select">
                    <option>Selecteer categorie..</option>
                    <option>Milieu</option>
                    <option>HRM</option>
                    <option>Financieel</option>
                    <option>Project</option>
                    <option>...</option>
                </select>
                <input id="user-input" class="form-control ml-3 col-6" type="text" placeholder="Search" aria-label="Search">
            </form>
        </div>
    </div>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 id="search-results-title" class="m-0 font-weight-bold text-primary">Alle VPI's</h6>
    </div>
    <div class="card-body" id="replaceable-content">
      {% include 'vpi/vpi-results-partial.html' %}   
    </div>
  </div>

{% endblock content %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static "vpi/js/vpi.js" %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
{% endblock scripts %}

vpi/templates/vpi/vpi-results-partial.html
{# vpi-results-partial.html #}
{% if vpis %}
  <div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>ID</th>
          <th>Naam</th>
          <th>Omschrijving</th>
          <th>Meeteenheid</th>
          <th>Actie</th>
        </tr>
      </thead>
      <tbody>
        {% for vpi in vpis %}
          <tr>
            <td>{{ vpi.id }}</td>
            <td>{{ vpi.name }}</td>
            <td>{{ vpi.description }}</td>
            <td>{{ vpi.measuring_unit }}</td>
            <td><a class="btn btn-primary btn-sm" href="{% url 'vpi:detail' vpi.id %}">Weergeven</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>   
  </div>
{% else %}
  <p class="mb-0">Geen VPI's gevonden.</p>
{% endif %}